name: Run

on:
  - push

jobs:
  run:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Compile main.kt
        run: kotlinc main.kt -cp games -cp solvers -include-runtime -d main.jar

      - name: Upload main.jar
        uses: actions/upload-artifact@v3
        with:
          name: main.jar
          path: main.jar

      - name: Run main.jar
        id: run
        run: |
          body="$(java -jar main.jar)"
          echo "body<<EOF" >> "$GITHUB_OUTPUT"
          echo "$body" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Comment result
        uses: peter-evans/commit-comment@v2
        with:
          body: ${{ steps.run.outputs.body }}
